events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://graduation-project-frontend-1:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api {
            proxy_pass http://graduation-project-backend-1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
